# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPXg1ooXKn58DaXSDVIFXr--zRu2BiDf
"""

import pandas as pd

test_data= pd.read_csv("/content/test.csv")

train_data= pd.read_csv("/content/train.csv")

train_data.head()

test_data.head()

train_data.info()

train_data.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

sns.heatmap(train_data.isnull())

train_data['Age'].fillna(train_data['Age'].mean(),inplace=True)
train_data['Embarked'].fillna(train_data['Embarked'].mode()[0],inplace=True)

test_data['Age'].fillna(test_data['Age'].mean(),inplace=True)
test_data['Fare'].fillna(test_data['Fare'].mean(),inplace=True)

train_data.isnull().sum().sort_values(ascending=False)

train_data=pd.get_dummies(train_data, columns=['Sex','Embarked'])
test_data=pd.get_dummies(test_data, columns=['Sex','Embarked'])

train_data.head()

X= train_data.drop(['Survived','Ticket', 'Name', 'Cabin', 'SibSp',	'Parch'],axis=1)
y=train_data['Survived']
X_test=test_data.drop(['Ticket', 'Name', 'Cabin' ],axis=1)

X.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train,y_train)

from sklearn.metrics import accuracy_score
y_pred=model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
accuracy

predictions = model.predict(test_data.drop(['Ticket', 'Name', 'Cabin', 'SibSp', 'Parch'], axis=1))

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

sns.barplot(x='Pclass', y='Survived', data=train_data)

